spring:
  application:
    name: config-server
  datasource:
    url: jdbc:mysql://localhost:3306/config?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/*.xml

server:
  port: 8081